backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

locale: ko

collections:
  - name: notices
    label: 공지사항
    label_singular: 공지
    folder: data/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "notice.html?slug={{slug}}"
    fields:
      - { label: 제목, name: title, widget: string }
      - { label: 내용 요약 (목록에 표시), name: summary, widget: string }
      - { label: 본문, name: body, widget: markdown }
      - { label: 작성자, name: author, widget: string, default: 관리자 }
      - { label: 날짜, name: date, widget: datetime, format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: 상단 고정 공지, name: pinned, widget: boolean, default: false }
